volumes:
  headscale_config:
    external: true
  headscale_lib:
    external: true
  headscale_run:
    external: true
    
networks:
  reverse-proxy:
    external: true

services:
  headscale:
    image: docker.io/headscale/headscale:<VERSION>
    restart: unless-stopped
    container_name: headscale
    hostname: headscale
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:9090:9090"
    volumes:
      # Please set <HEADSCALE_PATH> to the absolute path
      # of the previously created headscale directory.
      - headscale_config:/etc/headscale
      - headscale_lib:/var/lib/headscale
      - headscale_run:/var/run/headscale
    command: serve