volumes:
  nginx_data:
    external: true
  nginx_letsencrypt:
    external: true

networks:
  reverse-proxy:
    external: true

services:
  nginx:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt
    networks:
      - reverse-proxy
    ports:
      - 80:80
      - 443:443
      - 81:81
