networks:
  reverse-proxy:
    external: true

services:
  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    container_name: headscale-ui
    hostname: headscale-ui
    restart: unless-stopped
    networks:
      - reverse-proxy
    environment:
      - HTTPP_PORT=8080
    ports:
      - "8081:8080"