version: '3.8'

networks:
  reverse-proxy:
    external: true

services:
  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    container_name: headscale-ui
    restart: unless-stopped
    networks:
      - reverse-proxy
    environment:
      - VITE_HEADSCALE_URL=https://headscale.panalab.ddns-ip.net
      - VITE_HEADSCALE_API_KEY=F5uqeB9.LAP7p-NntKgVCqcUDCoXzkAkPghyR7HQ
    expose:
      - "80"  # espone internamente al reverse proxy
