networks:
  reverse-proxy:
    external: true

services:
  headscale-ui:
    image: ifargle/headscale-ui
    container_name: headscale-ui
    restart: unless-stopped
    networks:
      - reverse-proxy
    environment:
      - VITE_HEADSCALE_URL=https://headscale.panalab.ddns-ip.net
      - VITE_HEADSCALE_API_KEY=F5uqeB9.LAP7p-NntKgVCqcUDCoXzkAkPghyR7HQ
    ports:
      - "8081:80"
