networks:
  reverse-proxy:
    external: true

services:
  headscale-admin:
    image: goodieshq/headscale-admin:0.25
    container_name: headscale-admin
    restart: unless-stopped
    networks:
      - reverse-proxy
    